//
// Created by Xinxin Mei on 3/3/23.
//

#ifndef JANA4ML4FPGA_EVIOTCPBLOCKEDEVENTSOURCE_H
#define JANA4ML4FPGA_EVIOTCPBLOCKEDEVENTSOURCE_H



class EVIOTCPBlockedEventSource {

};


#endif //JANA4ML4FPGA_EVIOTCPBLOCKEDEVENTSOURCE_H
