#!/bin/bash

# Welcome message
echo "Welcome to the remote server!"

export ML4FPGA_TOP_DIR=/gluonfs1/home/hdtrdops/soft_ml4fpga

# Start conda environment
source $ML4FPGA_TOP_DIR/miniconda/etc/profile.d/conda.sh
# conda activate ml4fpga

# The path where edpm stores its JSon database and creates env files
export EDPM_DATA_PATH=$ML4FPGA_TOP_DIR/edpm_data

# This tells EDPM not to generate source thisroot.sh
export ROOT_INSTALLED_BY_CONDA=1

# source environment generated by EDPM
# means ROOT and others
source $EDPM_DATA_PATH/env.sh

source /gluonfs1/home/hdtrdops/soft_ml4fpga/miniconda/bin/activate ml4fpga

# Set an environment variable
# source /gluonfs1/home/hdtrdops/soft_ml4fpga/jana4ml4fpga/jana4ml4fpga-main/scripts/setup_env.sh

# You can add other initialization commands here
# For example, load a module or run a script
# module load python/3.8

# Start an interactive shell
#exec /usr/bin/bash
exec bash --login 
