#!/bin/bash

# Convenience launcher for the gluon farm: sets the install top directory,
# sources the environment generated by install_software.py (miniforge conda env +
# JANA2 framework + ROOT + jana4ml4fpga install paths + GLIBC_TUNABLES), then
# drops into an interactive login shell.
#
# Replaces the old miniconda + edpm flow (env.sh / ROOT_INSTALLED_BY_CONDA /
# miniconda/bin/activate); JANA2 is now built by the project, not edpm.

echo "Welcome to the remote server!"

export ML4FPGA_TOP_DIR=/gluonfs1/home/hdtrdops/soft_ml4fpga

# Environment generated by install_software.py (conda activate ml4fpga + all paths).
source "$ML4FPGA_TOP_DIR/setup_env.sh"

# Start an interactive login shell with the environment in place.
exec bash --login
